forbidden:
  - source: internal/.*/handler$
    imports:
      - internal/.*/repository$
allow:
  - source: internal/.*/handler$
    imports:
      - internal/.*/usecase$
      - internal/.*/model$
  - source: internal/.*/usecase$
    imports:
      - internal/.*/repository$
      - internal/.*/model$
  - source: internal/.*/repository$
    imports:
      - internal/.*/model$
